name: zephelin_trace_viewer
run-name: Zephelin Trace Viewer

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Prepare dependencies
        run: |
          corepack enable
          yarn
      - name: Lint code
        run: |
          yarn lint
          git diff --exit-code

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Prepare dependencies
        run: |
          corepack enable
          yarn
      - name: Build Zephelin Trace Viewer
        run: yarn build
      - name: Build Zephelin Trace Viewer in single-html mode
        run: yarn build-singlefile --outDir dist/single-html
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zephelin-trace-viewer
          path: dist
      - name: Deploy to Github Pages
        if: github.event_name == 'push' && github.repository == 'antmicro/zephelin-trace-viewer'
        run: |
          cd dist
          touch .nojekyll
          git init
          cp ../.git/config ./.git/config
          git add .
          git config --local user.email "push@gha"
          git config --local user.name "GHA"
          git commit -am "update ${{ github.sha }}"
          git push -u origin +HEAD:gh-pages
          rm -rf .git
